### ISSUE TITLE
GoLand 2021.1 is not supported

### ISSUE THREAD

**Issue by alex-held** [fe3dback/go-arch-lint#27]
Hey

The GoLand plugin does not support the new 2021.1 version.

<img width="448" alt="Screenshot 2021-04-10 at 08 56 35" src="https://user-images.githubusercontent.com/50153092/114261407-abd95780-99da-11eb-875b-53a15ee70cd7.png">

Can I help you to update it?

**Comment by fe3dback** [comment]
hi, now plugin is available on 2021.1
