### ISSUE TITLE
Add the linter to the golangci-lint

### ISSUE THREAD

**Issue by mcdoker18** [fe3dback/go-arch-lint#29]
It will be very useful, if go-arch-lint is added to the golangci-lint.
[How to add new linter to the golangci-lint](https://golangci-lint.run/contributing/new-linters/)

**Comment by fe3dback** [comment]
they require full unit test coverage. I do not want write unit test for coverage.
But i have service tests for each command, this cover most cases.

am not against integration with golangci-lint, but the guys do not want to
